/**
 * The site-wide social card generated by `app/opengraph-image.tsx`.
 *
 * Next.js replaces a parent's `openGraph` object wholesale when a page exports
 * its own, so a page that sets `openGraph` without `images` loses the card.
 * Spread this into such pages:
 *
 *   openGraph: { type: "website", url: "/about-us", images: [defaultShareImage] }
 */
export const defaultShareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  type: "image/png",
  alt: "Online Taleem ul Quran — Learn the Quran online with expert tutors",
};
